name: mfa-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.1
  - scikit-learn=1.2
  - librosa=0.10
  - matplotlib=3.7
  - seaborn=0.12
  - umap-learn=0.5
  - pip
  - pip:
    - torch==2.2.0

# To create the environment (PowerShell):
# conda env create -f environment-cpu.yml
# conda activate mfa-cpu
