base_channels: 64
batch_size: 32
config: null
data_dir: data/processed
device: auto
epochs: 100
experiment_name: multilabel_cnn_16genres_20251203_030619
genre_names_file: genre_names_16.json
labels_file: labels_multilabel.npy
lr: 0.001
multi_label: true
num_genres: 16
num_workers: 0
output_dir: models/trained_models
patience: 15
spectrogram_file: spectrograms.npy
test_split: 0.2
train_split: 0.6
use_attention: true
val_split: 0.2
weight_decay: 1.0e-05
