base_channels: 96
batch_size: 32
config: null
data_dir: data/processed
device: auto
epochs: 150
experiment_name: multilabel_cnn_70genres_20251203_113316
genre_names_file: genre_names_70.json
labels_file: labels_multilabel.npy
lr: 0.0005
multi_label: true
num_genres: 70
num_workers: 0
output_dir: models/trained_models
patience: 25
spectrogram_file: spectrograms.npy
test_split: 0.2
train_split: 0.6
use_attention: true
val_split: 0.2
weight_decay: 1.0e-05
